# 异常处理

## 内置异常类

异常 | 描述
-|-




## 异常捕获

* 捕获一个异常
```js
try{
	//可能会报错的代码
} catch (Exception e) { //如果发生了错误  不会报错终止程序，而是进入catch中
						// e 记录着错误 信息, 错误类型多种多样
	e.printStackTrace();//记录日志
	throw new ServletException(e);	//抛出错误  这样就终止程序了
}

```

* 默认异常的处理方法

	在java 中默认产生了异常会向上抛,如果上层有catch捕获了错误就不继续向上，
	如果没有捕获，则继续向上抛，直到抛到jvm之后线程结束了。抛出错误

	通过try catch 可以让代码更健壮  不会那么容易挂掉




* 一个方法抛出异常，这个方法必须声明异常的抛出

```java
package tryCatch;
import java.io.*;
public class TryCatch {
	public static void main(String[] args) {
		try {
			int[] a = new int[3];
			System.out.println("输出a4" + a[7]);
		} catch(ArrayIndexOutOfBoundsException  e) { //
			System.out.println(e);
		}
	}
}
```

## throws Exception

	在方法之后，表示这个方法不处理异常，谁调用这个方法就由谁处理异常 而且必须处理

	```java
		public List <Employee> findAll() throws Exception;
		//同样适用于  接口中的方法
	```


## throws/throw

throw放在方法签名的尾部

```java
import java.io.*;
public class className
{
  public void deposit(double amount) throws RemoteException
  {
    // Method implementation
    throw new RemoteException();
  }
  //Remainder of class definition
}
```


## servlet 异常抛出

```java
public class OServlet extends HttpServlet{
	public void service (HttpServletRequest request, HttpServletResponse response) throws ServletException,IOException}{
		//方法 形参后面添加  要抛出的错误类型 用逗号隔开
		try{
			//*********	  可能发生错误的代码
		}catch(Exception e){//如果发生错误，会进入   e保存错误信息
			e.printStackTrace(); //记录日志
			throw new ServletException(e); //抛出错误
		}
	}
}
```

## 配置 错误页面

* 在**web.xml**中配置

```xml
<errpr-page>
	<errpr-page>500</errpr-page>
	<location>/error.html</location>
</errpr-page>
```

